FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_FASTLINK_API_URL
ARG VITE_FASTLINK_ENVIRONMENT=SANDBOX
ARG VITE_PUBLIC_BASE=/
ARG RAILWAY_GIT_COMMIT_SHA=unknown
ENV VITE_FASTLINK_API_URL=$VITE_FASTLINK_API_URL
ENV VITE_FASTLINK_ENVIRONMENT=$VITE_FASTLINK_ENVIRONMENT
ENV VITE_PUBLIC_BASE=$VITE_PUBLIC_BASE
ENV VITE_FASTLINK_BUILD_SHA=$RAILWAY_GIT_COMMIT_SHA
RUN npm run build

FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
