server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location /api/ {
    proxy_ssl_server_name on;
    proxy_set_header Host fastlink-backend-dev-development-a.up.railway.app;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass https://fastlink-backend-dev-development-a.up.railway.app;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
