#!/usr/bin/env bash
set -euo pipefail

: "${FASTLINK_ENVIRONMENT:?FASTLINK_ENVIRONMENT is required}"
: "${FASTLINK_BUILD_SHA:?FASTLINK_BUILD_SHA is required}"

FASTLINK_INTERACTION_MODE="${FASTLINK_INTERACTION_MODE:-FULL}"

case "$FASTLINK_ENVIRONMENT" in
  SANDBOX|TEST|PRODUCTION) ;;
  *) echo "FASTLINK_ENVIRONMENT must be SANDBOX, TEST, or PRODUCTION" >&2; exit 1 ;;
esac

case "$FASTLINK_INTERACTION_MODE" in
  FULL|READ_ONLY_UAT) ;;
  *) echo "FASTLINK_INTERACTION_MODE must be FULL or READ_ONLY_UAT" >&2; exit 1 ;;
esac

if [[ "$FASTLINK_INTERACTION_MODE" = "READ_ONLY_UAT" && "$FASTLINK_ENVIRONMENT" != "TEST" ]]; then
  echo "READ_ONLY_UAT is allowed only in TEST" >&2
  exit 1
fi

if [[ ! "$FASTLINK_BUILD_SHA" =~ ^[0-9a-fA-F]{40}$ ]]; then
  echo "FASTLINK_BUILD_SHA must be a full Git SHA" >&2
  exit 1
fi

VITE_FASTLINK_ENVIRONMENT="$FASTLINK_ENVIRONMENT" \
VITE_FASTLINK_API_URL="/api" \
VITE_FASTLINK_BUILD_SHA="$FASTLINK_BUILD_SHA" \
VITE_FASTLINK_INTERACTION_MODE="$FASTLINK_INTERACTION_MODE" \
VITE_FASTLINK_DATA_SOURCE="backend" \
VITE_PUBLIC_BASE="/" \
npm run build

npm run test:cloudflare
