import {FormEvent,useEffect,useState} from 'react'
import {ArrowRightLeft,CreditCard,Landmark,LogOut,RefreshCw,ShieldCheck,Snowflake,WalletCards} from 'lucide-react'
import {WalletAccountRecord,walletApi,walletRuntime,WalletApiError,WalletCredentials,WalletSession,WalletTransactionPage} from './apiClient'

type CardRecord={id:string;status?:string;last4?:string;[key:string]:unknown}

export default function App(){
 const[mode,setMode]=useState<'login'|'register'>('login')
 const[tenantId,setTenantId]=useState('')
 const[email,setEmail]=useState('')
 const[password,setPassword]=useState('')
 const[session,setSession]=useState<WalletSession|null>(null)
 const[accounts,setAccounts]=useState<WalletAccountRecord[]>([])
 const[selectedAccount,setSelectedAccount]=useState<WalletAccountRecord|null>(null)
 const[accountBalance,setAccountBalance]=useState<Record<string,unknown>|null>(null)
 const[walletTransactions,setWalletTransactions]=useState<WalletTransactionPage|null>(null)
 const[destinationAccountId,setDestinationAccountId]=useState('')
 const[transferAmount,setTransferAmount]=useState('')
 const[cards,setCards]=useState<CardRecord[]>([])
 const[selectedCard,setSelectedCard]=useState<CardRecord|null>(null)
 const[cardBalance,setCardBalance]=useState<Record<string,unknown>|null>(null)
 const[cardTransactions,setCardTransactions]=useState<Record<string,unknown>|null>(null)
 const[busy,setBusy]=useState(true)
 const[error,setError]=useState('')
 const describe=(value:unknown)=>value instanceof WalletApiError?`${value.message}`:value instanceof Error?value.message:'Unknown API error'
 const clear=()=>{setSession(null);setAccounts([]);setSelectedAccount(null);setAccountBalance(null);setWalletTransactions(null);setCards([]);setSelectedCard(null);setCardBalance(null);setCardTransactions(null)}
 const loadWallet=async(account:WalletAccountRecord)=>{const[balance,transactions]=await Promise.all([walletApi.walletBalance(account.id),walletApi.walletTransactions(account.id)]);setSelectedAccount(account);setAccountBalance(balance);setWalletTransactions(transactions)}
 const loadCard=async(card:CardRecord)=>{const[detail,balance,transactions]=await Promise.all([walletApi.card(card.id) as Promise<CardRecord>,walletApi.balance(card.id),walletApi.transactions(card.id)]);setSelectedCard(detail);setCards(current=>current.map(row=>row.id===detail.id?detail:row));setCardBalance(balance);setCardTransactions(transactions)}
 const acceptSession=async(current:WalletSession)=>{if(current.environment!==walletRuntime.environment)throw new Error(`Build environment ${walletRuntime.environment} does not match session ${current.environment}`);const[cardRows,accountRows]=await Promise.all([walletApi.cards() as Promise<CardRecord[]>,walletApi.walletAccounts()]);setSession(current);setCards(cardRows);setAccounts(accountRows);const card=cardRows[0]||null;const account=accountRows[0]||null;setSelectedCard(card);setSelectedAccount(account);if(card)await loadCard(card);if(account)await loadWallet(account)}
 useEffect(()=>{void (async()=>{try{await acceptSession(await walletApi.session())}catch(value){clear();if(!(value instanceof WalletApiError&&value.status===401))setError(describe(value))}finally{setBusy(false)}})()},[])
 const authenticate=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');clear();try{const credentials:WalletCredentials={tenantId:tenantId.trim(),email:email.trim(),password};const current=mode==='login'?await walletApi.login(credentials):await walletApi.register(credentials);await acceptSession(current);setPassword('')}catch(value){clear();setError(describe(value))}finally{setBusy(false)}}
 const reloadCard=async()=>{if(!session||!selectedCard)return;setBusy(true);setError('');try{await loadCard(selectedCard)}catch(value){setError(describe(value))}finally{setBusy(false)}}
 const toggle=async()=>{if(!session||!selectedCard)return;setBusy(true);setError('');try{const frozen=String(selectedCard.status).toUpperCase()==='FROZEN';await(frozen?walletApi.unfreeze(selectedCard.id):walletApi.freeze(selectedCard.id));await loadCard(selectedCard)}catch(value){setError(describe(value))}finally{setBusy(false)}}
 const transfer=async(event:FormEvent)=>{event.preventDefault();if(!selectedAccount)return;setBusy(true);setError('');try{await walletApi.internalTransfer({sourceAccountId:selectedAccount.id,destinationAccountId:destinationAccountId.trim(),assetCode:selectedAccount.assetCode,amount:transferAmount});const refreshed=await walletApi.walletAccounts();setAccounts(refreshed);const account=refreshed.find(row=>row.id===selectedAccount.id);if(account)await loadWallet(account);setTransferAmount('')}catch(value){setError(describe(value))}finally{setBusy(false)}}
 const refresh=async()=>{if(!session)return;setBusy(true);setError('');try{await acceptSession(await walletApi.refresh())}catch(value){clear();setError(describe(value))}finally{setBusy(false)}}
 const logout=async()=>{setBusy(true);setError('');try{await walletApi.logout()}catch(value){if(!(value instanceof WalletApiError&&value.status===401))setError(describe(value))}finally{clear();setPassword('');setBusy(false)}}
 return <main style={{maxWidth:980,margin:'40px auto',padding:24,fontFamily:'Inter,system-ui'}}>
  <header><div><h1>FastLink Wallet</h1><p>Environment: <b>{walletRuntime.environment}</b> · Build: <b>{walletRuntime.buildSha}</b></p><p>API: <code>{walletRuntime.apiUrl}</code></p></div>{session&&<div className="session-actions"><button onClick={refresh} disabled={busy}><RefreshCw/> Refresh session</button><button onClick={logout} disabled={busy}><LogOut/> Sign out</button></div>}</header>
  {!session&&<section className="panel auth-panel"><ShieldCheck/><h2>{mode==='login'?'Sign in to FastLink':'Create your FastLink account'}</h2><p>Authentication is handled by the FastLink Backend using a secure HttpOnly cookie. Browser storage and pasted bearer tokens are disabled.</p><form onSubmit={authenticate}><label>Workspace<input value={tenantId} onChange={event=>setTenantId(event.target.value)} placeholder="Tenant ID or slug" autoComplete="organization" required/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Minimum 12 characters" autoComplete={mode==='login'?'current-password':'new-password'} minLength={12} required/></label><button disabled={busy||!tenantId.trim()||!email.trim()||password.length<12}>{busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button></form><button className="mode-switch" onClick={()=>{setMode(current=>current==='login'?'register':'login');setError('')}}>{mode==='login'?'New to FastLink? Register':'Already registered? Sign in'}</button></section>}
  {error&&<section className="panel"><h3>API unavailable</h3><p>{error}</p><p>Unavailable · no stale data displayed.</p></section>}
  {session&&<div className="wallet-grid">
   <section className="panel"><div className="panel-row"><h2><Landmark/> Real wallet balances</h2>{selectedAccount&&<button onClick={()=>void loadWallet(selectedAccount)} disabled={busy}><RefreshCw/> Refresh</button>}</div>{accounts.length===0?<p>Unavailable · no wallet accounts returned by Backend.</p>:<select value={selectedAccount?.id||''} onChange={event=>{const account=accounts.find(row=>row.id===event.target.value);if(account)void loadWallet(account)}}>{accounts.map(account=><option key={account.id} value={account.id}>{account.assetCode} · {account.availableBalance} · {account.status}</option>)}</select>}{selectedAccount&&<><div className="balance-record"><b>{selectedAccount.assetCode} {String(accountBalance?.availableBalance??selectedAccount.availableBalance)}</b><small>Persisted Backend balance · Account {selectedAccount.id}</small></div><form className="transfer-form" onSubmit={transfer}><h3><ArrowRightLeft/> Internal transfer</h3><input value={destinationAccountId} onChange={event=>setDestinationAccountId(event.target.value)} placeholder="Destination wallet account ID" required/><input value={transferAmount} onChange={event=>setTransferAmount(event.target.value)} inputMode="decimal" pattern="^[0-9]+(?:\\.[0-9]{1,18})?$" placeholder={`Amount in ${selectedAccount.assetCode}`} required/><button disabled={busy||!destinationAccountId.trim()||!transferAmount}>Transfer</button></form><div className="record-list"><h3>Wallet transactions</h3>{walletTransactions?.items.length?walletTransactions.items.map(row=><p key={row.id}><span>{row.type} · {row.status}</span><b>{row.amount} {row.assetCode}</b></p>):<p>No persisted transactions returned.</p>}</div></>}</section>
   <section className="panel"><div className="panel-row"><h2><WalletCards/> Real cards</h2><button onClick={reloadCard} disabled={busy||!selectedCard}><RefreshCw/> Refresh</button></div>{cards.length===0?<p>Unavailable · no cards returned by Backend.</p>:<select value={selectedCard?.id||''} onChange={event=>{const card=cards.find(row=>row.id===event.target.value);if(card)void loadCard(card)}}>{cards.map(card=><option key={card.id} value={card.id}>{card.last4?`•••• ${card.last4}`:card.id} · {String(card.status||'UNKNOWN')}</option>)}</select>}{selectedCard&&<><div className="balance-record"><CreditCard/><b>{selectedCard.last4?`Card •••• ${selectedCard.last4}`:selectedCard.id}</b><small>Status: {String(selectedCard.status||'Unavailable')}</small><small>Balance: {String(cardBalance?.availableBalanceMinor??'Unavailable')}</small></div><button onClick={toggle} disabled={busy}><Snowflake/> {String(selectedCard.status).toUpperCase()==='FROZEN'?'Unfreeze':'Freeze'}</button><div className="record-list"><h3>Card transactions</h3><pre>{JSON.stringify(cardTransactions,null,2)}</pre></div></>}</section>
  </div>}
 </main>
}
