import {FormEvent,useEffect,useRef,useState} from 'react'
import {ArrowRightLeft,CreditCard,Landmark,LogOut,RefreshCw,ShieldCheck,Snowflake,WalletCards} from 'lucide-react'
import {WalletAccountRecord,walletApi,walletRuntime,WalletApiError,WalletCredentials,WalletSession,WalletTransactionPage} from './apiClient'
import {CardRecord,cardRequestIsCurrent,cardStatusActionDecision,mergeCardPages} from './cardList'

const sessionScope=(session:WalletSession)=>JSON.stringify([session.actorId,session.tenantId,session.customerId,session.environment])

export default function App(){
 const[mode,setMode]=useState<'login'|'register'>('login')
 const[tenantId,setTenantId]=useState('')
 const[email,setEmail]=useState('')
 const[password,setPassword]=useState('')
 const[session,setSession]=useState<WalletSession|null>(null)
 const[accounts,setAccounts]=useState<WalletAccountRecord[]>([])
 const[selectedAccount,setSelectedAccount]=useState<WalletAccountRecord|null>(null)
 const[accountBalance,setAccountBalance]=useState<Record<string,unknown>|null>(null)
 const[walletTransactions,setWalletTransactions]=useState<WalletTransactionPage|null>(null)
 const[destinationAccountId,setDestinationAccountId]=useState('')
 const[transferAmount,setTransferAmount]=useState('')
 const[cards,setCards]=useState<CardRecord[]>([])
 const[cardNextCursor,setCardNextCursor]=useState<string|null>(null)
 const[cardListLoadingMore,setCardListLoadingMore]=useState(false)
 const[cardListError,setCardListError]=useState('')
 const[selectedCard,setSelectedCard]=useState<CardRecord|null>(null)
 const[cardBalance,setCardBalance]=useState<Record<string,unknown>|null>(null)
 const[cardTransactions,setCardTransactions]=useState<Record<string,unknown>|null>(null)
 const[busy,setBusy]=useState(true)
 const[error,setError]=useState('')
 const cardRequestSequence=useRef(0)
 const cardScope=useRef<string|null>(null)
 const cardDetailRequestSequence=useRef(0)
 const cardDetailTarget=useRef<string|null>(null)
 const cardActionRequestSequence=useRef(0)
 const cardActionTarget=useRef<string|null>(null)
 const describe=(value:unknown)=>value instanceof WalletApiError?`${value.message}`:value instanceof Error?value.message:'Unknown API error'
 const invalidateCardDetail=()=>{cardDetailRequestSequence.current+=1;cardDetailTarget.current=null;cardActionRequestSequence.current+=1;cardActionTarget.current=null}
 const clear=()=>{cardRequestSequence.current+=1;cardScope.current=null;invalidateCardDetail();setSession(null);setAccounts([]);setSelectedAccount(null);setAccountBalance(null);setWalletTransactions(null);setCards([]);setCardNextCursor(null);setCardListLoadingMore(false);setCardListError('');setSelectedCard(null);setCardBalance(null);setCardTransactions(null)}
 const loadWallet=async(account:WalletAccountRecord)=>{const[balance,transactions]=await Promise.all([walletApi.walletBalance(account.id),walletApi.walletTransactions(account.id)]);setSelectedAccount(account);setAccountBalance(balance);setWalletTransactions(transactions)}
 const loadCard=async(card:CardRecord,expectedScope=cardScope.current,callbacks?:{onError?:(value:unknown)=>void;onSettled?:()=>void})=>{cardActionRequestSequence.current+=1;cardActionTarget.current=null;const request={requestId:++cardDetailRequestSequence.current,scopeKey:expectedScope,cardId:card.id};cardDetailTarget.current=card.id;const isCurrent=()=>cardRequestIsCurrent(request,cardDetailRequestSequence.current,cardScope.current,cardDetailTarget.current);try{const[detail,balance,transactions]=await Promise.all([walletApi.card(card.id),walletApi.balance(card.id),walletApi.transactions(card.id)]);if(!isCurrent())return;setSelectedCard(detail);setCards(current=>current.map(row=>row.id===detail.id?detail:row));setCardBalance(balance);setCardTransactions(transactions)}catch(value){if(!isCurrent())return;if(callbacks?.onError)callbacks.onError(value);else throw value}finally{if(isCurrent())callbacks?.onSettled?.()}}
 const acceptSession=async(current:WalletSession)=>{if(current.environment!==walletRuntime.environment)throw new Error(`Build environment ${walletRuntime.environment} does not match session ${current.environment}`);const scope=sessionScope(current);cardScope.current=scope;invalidateCardDetail();const requestId=++cardRequestSequence.current;setCards([]);setCardNextCursor(null);setCardListError('');setSelectedCard(null);setCardBalance(null);setCardTransactions(null);const[cardPage,accountRows]=await Promise.all([walletApi.cards(),walletApi.walletAccounts()]);if(cardScope.current!==scope||cardRequestSequence.current!==requestId)return;setSession(current);setCards(cardPage.cards);setCardNextCursor(cardPage.nextCursor);setAccounts(accountRows);const card=cardPage.cards[0]||null;const account=accountRows[0]||null;setSelectedCard(card);setSelectedAccount(account);if(card)await loadCard(card,scope);if(account)await loadWallet(account)}
 const loadMoreCards=async()=>{if(!session||!cardNextCursor||cardListLoadingMore)return;const scope=sessionScope(session);if(scope!==cardScope.current)return;const cursor=cardNextCursor;const requestId=++cardRequestSequence.current;setCardListLoadingMore(true);setCardListError('');try{const page=await walletApi.cards(cursor);if(cardScope.current!==scope||cardRequestSequence.current!==requestId)return;setCards(current=>mergeCardPages(current,page.cards));setCardNextCursor(page.nextCursor)}catch(value){if(cardScope.current===scope&&cardRequestSequence.current===requestId)setCardListError(describe(value))}finally{if(cardScope.current===scope&&cardRequestSequence.current===requestId)setCardListLoadingMore(false)}}
 useEffect(()=>{void (async()=>{try{await acceptSession(await walletApi.session())}catch(value){clear();if(!(value instanceof WalletApiError&&value.status===401))setError(describe(value))}finally{setBusy(false)}})()},[])
 const authenticate=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');clear();try{const credentials:WalletCredentials={tenantId:tenantId.trim(),email:email.trim(),password};const current=mode==='login'?await walletApi.login(credentials):await walletApi.register(credentials);await acceptSession(current);setPassword('')}catch(value){clear();setError(describe(value))}finally{setBusy(false)}}
 const detailCallbacks={onError:(value:unknown)=>setError(describe(value)),onSettled:()=>setBusy(false)}
 const selectCard=async(card:CardRecord)=>{if(!session)return;setBusy(true);setError('');setSelectedCard(card);setCardBalance(null);setCardTransactions(null);await loadCard(card,sessionScope(session),detailCallbacks)}
 const reloadCard=async()=>{if(!session||!selectedCard)return;setBusy(true);setError('');await loadCard(selectedCard,sessionScope(session),detailCallbacks)}
 const toggleDecision=selectedCard?cardStatusActionDecision(selectedCard,session?sessionScope(session):null,cardScope.current,cardDetailTarget.current):null
 const toggle=async()=>{if(!session||!selectedCard)return;const scope=sessionScope(session);const card=selectedCard;const decision=cardStatusActionDecision(card,scope,cardScope.current,cardDetailTarget.current);if(!decision.allowed||!decision.operation){if(scope===cardScope.current&&card.id===cardDetailTarget.current)setError(`Card operation blocked · ${decision.reason??'Capability unavailable.'}`);return}const request={requestId:++cardActionRequestSequence.current,scopeKey:scope,cardId:card.id};cardActionTarget.current=card.id;const isCurrent=()=>cardRequestIsCurrent(request,cardActionRequestSequence.current,cardScope.current,cardActionTarget.current);setBusy(true);setError('');try{await(decision.operation==='unfreeze'?walletApi.unfreeze(card.id):walletApi.freeze(card.id));if(!isCurrent())return;await loadCard(card,scope,detailCallbacks)}catch(value){if(isCurrent()){setError(describe(value));setBusy(false)}}}
 const transfer=async(event:FormEvent)=>{event.preventDefault();if(!selectedAccount)return;setBusy(true);setError('');try{await walletApi.internalTransfer({sourceAccountId:selectedAccount.id,destinationAccountId:destinationAccountId.trim(),assetCode:selectedAccount.assetCode,amount:transferAmount});const refreshed=await walletApi.walletAccounts();setAccounts(refreshed);const account=refreshed.find(row=>row.id===selectedAccount.id);if(account)await loadWallet(account);setTransferAmount('')}catch(value){setError(describe(value))}finally{setBusy(false)}}
 const refresh=async()=>{if(!session)return;setBusy(true);setError('');try{await acceptSession(await walletApi.refresh())}catch(value){clear();setError(describe(value))}finally{setBusy(false)}}
 const logout=async()=>{setBusy(true);setError('');try{await walletApi.logout()}catch(value){if(!(value instanceof WalletApiError&&value.status===401))setError(describe(value))}finally{clear();setPassword('');setBusy(false)}}
 return <main style={{maxWidth:980,margin:'40px auto',padding:24,fontFamily:'Inter,system-ui'}}>
  <header><div><h1>FastLink Wallet</h1><p>Environment: <b>{walletRuntime.environment}</b> · Build: <b>{walletRuntime.buildSha}</b></p><p>API: <code>{walletRuntime.apiUrl}</code></p></div>{session&&<div className="session-actions"><button onClick={refresh} disabled={busy}><RefreshCw/> Refresh session</button><button onClick={logout} disabled={busy}><LogOut/> Sign out</button></div>}</header>
  {!session&&<section className="panel auth-panel"><ShieldCheck/><h2>{mode==='login'?'Sign in to FastLink':'Create your FastLink account'}</h2><p>Authentication is handled by the FastLink Backend using a secure HttpOnly cookie. Browser storage and pasted bearer tokens are disabled.</p><form onSubmit={authenticate}><label>Workspace<input value={tenantId} onChange={event=>setTenantId(event.target.value)} placeholder="Tenant ID or slug" autoComplete="organization" required/></label><label>Email<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Minimum 12 characters" autoComplete={mode==='login'?'current-password':'new-password'} minLength={12} required/></label><button disabled={busy||!tenantId.trim()||!email.trim()||password.length<12}>{busy?'Please wait…':mode==='login'?'Sign in':'Register'}</button></form><button className="mode-switch" onClick={()=>{setMode(current=>current==='login'?'register':'login');setError('')}}>{mode==='login'?'New to FastLink? Register':'Already registered? Sign in'}</button></section>}
  {error&&<section className="panel"><h3>API unavailable</h3><p>{error}</p><p>Unavailable · no stale data displayed.</p></section>}
  {session&&<div className="wallet-grid">
   <section className="panel"><div className="panel-row"><h2><Landmark/> Real wallet balances</h2>{selectedAccount&&<button onClick={()=>void loadWallet(selectedAccount)} disabled={busy}><RefreshCw/> Refresh</button>}</div>{accounts.length===0?<p>Unavailable · no wallet accounts returned by Backend.</p>:<select value={selectedAccount?.id||''} onChange={event=>{const account=accounts.find(row=>row.id===event.target.value);if(account)void loadWallet(account)}}>{accounts.map(account=><option key={account.id} value={account.id}>{account.assetCode} · {account.availableBalance} · {account.status}</option>)}</select>}{selectedAccount&&<><div className="balance-record"><b>{selectedAccount.assetCode} {String(accountBalance?.availableBalance??selectedAccount.availableBalance)}</b><small>Persisted Backend balance · Account {selectedAccount.id}</small></div><form className="transfer-form" onSubmit={transfer}><h3><ArrowRightLeft/> Internal transfer</h3><input value={destinationAccountId} onChange={event=>setDestinationAccountId(event.target.value)} placeholder="Destination wallet account ID" required/><input value={transferAmount} onChange={event=>setTransferAmount(event.target.value)} inputMode="decimal" pattern="^[0-9]+(?:\\.[0-9]{1,18})?$" placeholder={`Amount in ${selectedAccount.assetCode}`} required/><button disabled={busy||!destinationAccountId.trim()||!transferAmount}>Transfer</button></form><div className="record-list"><h3>Wallet transactions</h3>{walletTransactions?.items.length?walletTransactions.items.map(row=><p key={row.id}><span>{row.type} · {row.status}</span><b>{row.amount} {row.assetCode}</b></p>):<p>No persisted transactions returned.</p>}</div></>}</section>
   <section className="panel"><div className="panel-row"><h2><WalletCards/> Real cards</h2><button onClick={reloadCard} disabled={busy||!selectedCard}><RefreshCw/> Refresh</button></div>{cards.length===0?<p>Unavailable · no cards returned by Backend.</p>:<select value={selectedCard?.id||''} onChange={event=>{const card=cards.find(row=>row.id===event.target.value);if(card)void selectCard(card)}}>{cards.map(card=><option key={card.id} value={card.id}>{card.last4?`•••• ${card.last4}`:card.id} · {card.status}</option>)}</select>}{cardListError&&<p className="inline-error">{cardListError} · Current cards remain scoped to this session.</p>}{cardNextCursor&&<button className="load-more" onClick={()=>void loadMoreCards()} disabled={busy||cardListLoadingMore}>{cardListLoadingMore?'Loading more cards…':'Load more cards'}</button>}{selectedCard&&<><div className="balance-record"><CreditCard/><b>{selectedCard.last4?`Card •••• ${selectedCard.last4}`:selectedCard.id}</b><small>Status: {selectedCard.status}</small><small>Balance: {String(cardBalance?.availableBalanceMinor??selectedCard.availableBalanceMinor??'Unavailable')}</small></div><button onClick={toggle} disabled={busy||!toggleDecision?.allowed} title={toggleDecision?.reason??undefined}><Snowflake/> {toggleDecision?.label??'Card action unavailable'}</button>{toggleDecision?.reason&&<p className="card-action-note">{toggleDecision.reason}</p>}<div className="record-list"><h3>Card transactions</h3><pre>{JSON.stringify(cardTransactions,null,2)}</pre></div></>}</section>
  </div>}
 </main>
}
